INSERT INTO daily_questions (subject, question, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, generated_at) VALUES 
('Mathematics', 'What is the value of sin(30°)?', '0.5', '0.707', '0.866', '1.0', 'A', 'sin(30°) = 1/2 = 0.5', 'medium', NOW()),
('Mathematics', 'If 2x + 3 = 11, what is the value of x?', '2', '4', '6', '8', 'B', '2x = 11 - 3 = 8, so x = 4', 'medium', NOW()),
('Mathematics', 'What is the area of a circle with radius 7cm?', '154 cm²', '44 cm²', '22 cm²', '308 cm²', 'A', 'Area = πr² = (22/7) × 7² = 154 cm²', 'medium', NOW()),
('Mathematics', 'Simplify: (x² - 4)/(x - 2)', 'x + 2', 'x - 2', '2x', 'x²', 'A', '(x² - 4) = (x + 2)(x - 2)', 'medium', NOW()),
('Mathematics', 'What is the next term in the sequence: 2, 6, 18, 54?', '108', '162', '216', '324', 'B', 'Each term is multiplied by 3', 'medium', NOW()),
('Physics', 'What is the unit of electric current?', 'Volt', 'Ampere', 'Ohm', 'Watt', 'B', 'The unit of electric current is Ampere', 'medium', NOW()),
('Physics', 'Which law states that energy cannot be created or destroyed?', 'Newton first law', 'Law of conservation of energy', 'Ohms law', 'Hookes law', 'B', 'The law of conservation of energy', 'medium', NOW()),
('Physics', 'What is the acceleration due to gravity on Earth?', '9.8 m/s²', '8.9 m/s²', '10.8 m/s²', '11.2 m/s²', 'A', 'Gravity is approximately 9.8 m/s²', 'medium', NOW()),
('Physics', 'Which of the following is a vector quantity?', 'Speed', 'Mass', 'Velocity', 'Energy', 'C', 'Velocity has magnitude and direction', 'medium', NOW()),
('Physics', 'What type of lens is used to correct short-sightedness?', 'Convex lens', 'Concave lens', 'Cylindrical lens', 'Bifocal lens', 'B', 'Concave lens corrects myopia', 'medium', NOW()),
('Chemistry', 'What is the atomic number of carbon?', '4', '6', '8', '12', 'B', 'Carbon has 6 protons', 'medium', NOW()),
('Chemistry', 'Which gas is produced when acid reacts with metal?', 'Oxygen', 'Carbon dioxide', 'Hydrogen', 'Nitrogen', 'C', 'Acid + metal produces hydrogen gas', 'medium', NOW()),
('Chemistry', 'What is the chemical formula of water?', 'H2O', 'CO2', 'NaCl', 'CH4', 'A', 'Water is H2O', 'medium', NOW()),
('Chemistry', 'Which of the following is an alkali metal?', 'Iron', 'Sodium', 'Chlorine', 'Carbon', 'B', 'Sodium is in Group 1', 'medium', NOW()),
('Chemistry', 'What is the pH of pure water at 25°C?', '5', '6', '7', '8', 'C', 'Pure water is neutral with pH 7', 'medium', NOW()),
('Biology', 'Which organelle is the powerhouse of the cell?', 'Nucleus', 'Mitochondria', 'Ribosome', 'Vacuole', 'B', 'Mitochondria produce ATP', 'medium', NOW()),
('Biology', 'What is the process by which plants make food?', 'Respiration', 'Photosynthesis', 'Digestion', 'Excretion', 'B', 'Photosynthesis uses sunlight', 'medium', NOW()),
('Biology', 'Which blood vessel carries blood from the heart?', 'Vein', 'Artery', 'Capillary', 'Venule', 'B', 'Arteries carry blood away from heart', 'medium', NOW()),
('Biology', 'What is the basic unit of heredity?', 'Cell', 'Gene', 'Chromosome', 'DNA', 'B', 'Gene determines traits', 'medium', NOW()),
('Biology', 'Which system is responsible for gas exchange?', 'Circulatory', 'Digestive', 'Respiratory', 'Nervous', 'C', 'Respiratory system exchanges gases', 'medium', NOW()),
('English', 'Choose the correct spelling:', 'Occassion', 'Occasion', 'Ocasion', 'Ocassion', 'B', 'Correct spelling is Occasion', 'medium', NOW()),
('English', 'What is the plural of child?', 'Childs', 'Childes', 'Children', 'Childrens', 'C', 'Irregular plural is children', 'medium', NOW()),
('English', 'The classroom was a zoo is what figure of speech?', 'Simile', 'Metaphor', 'Personification', 'Alliteration', 'B', 'Direct comparison is metaphor', 'medium', NOW()),
('English', 'What is the past tense of go?', 'Goed', 'Went', 'Gone', 'Going', 'B', 'Irregular verb: go-went-gone', 'medium', NOW()),
('English', 'What type of noun is happiness?', 'Concrete', 'Abstract', 'Collective', 'Proper', 'B', 'Happiness is an abstract concept', 'medium', NOW());