import React from 'react';
import { Link } from 'react-router-dom';
import {
  CheckCircle as CheckCircleIcon,
  BookOpen as BookOpenIcon,
  BarChart3 as ChartBarIcon,
  Smartphone as DevicePhoneMobileIcon,
  Clock as ClockIcon,
  Trophy as TrophyIcon
} from 'lucide-react';

const features = [
  {
    name: 'AI-Powered Questions',
    description: 'Get personalized questions generated by advanced AI tailored to your learning needs.',
    icon: BookOpenIcon,
  },
  {
    name: 'Smart Analytics',
    description: 'Track your progress with detailed analytics and performance insights.',
    icon: ChartBarIcon,
  },
  {
    name: 'Mobile Optimized',
    description: 'Practice anywhere with our Progressive Web App that works like a native mobile app.',
    icon: DevicePhoneMobileIcon,
  },
  {
    name: 'Daily Practice',
    description: '50 fresh questions per subject every 3 days to keep your practice consistent.',
    icon: ClockIcon,
  },
  {
    name: 'JAMB Score Prediction',
    description: 'Get accurate predictions of your potential JAMB score based on your practice performance.',
    icon: TrophyIcon,
  },
  {
    name: 'Offline Support',
    description: 'Continue practicing even without internet connection with our offline capabilities.',
    icon: CheckCircleIcon,
  },
];

const testimonials = [
  {
    name: 'Adebayo Johnson',
    role: 'JAMB 2024 Candidate',
    image: '/images/nigerian-jamb-exam-students-computer-lab-study.jpg',
    quote: 'This app helped me improve my scores by 40 points. The AI questions were exactly what I needed!'
  },
  {
    name: 'Fatima Mohammed',
    role: 'University of Lagos Student',
    image: '/images/Nigerian-JAMB-Exam-Students-Computer-Lab-Study.jpg',
    quote: 'The detailed explanations and progress tracking made all the difference in my preparation.'
  }
];

export default function HomePage() {
  // Add error state
  const [error, setError] = React.useState<string | null>(null);

  // Simple ping to test if backend is accessible
  React.useEffect(() => {
    const checkServerConnection = async () => {
      try {
        const response = await fetch('https://zjfilhbczaquokqlcoej.supabase.co/rest/v1/', {
          method: 'GET',
          headers: {
            'apikey': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZmlsaGJjemFxdW9rcWxjb2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzQ2MjIsImV4cCI6MjA3MTExMDYyMn0.b6YATor8UyDwYSiSagOQUxM_4sqfCv-89CBXVgC2hP0'
          }
        });
        
        if (!response.ok) {
          console.warn('Supabase connection issue. Status:', response.status);
        } else {
          console.log('Supabase connection successful');
        }
      } catch (err) {
        console.error('Failed to connect to Supabase:', err);
        setError('Unable to connect to the server. Please check your internet connection and try again.');
      }
    };
    
    checkServerConnection();
  }, []);

  // Error message display
  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4">
        <div className="max-w-md w-full bg-white shadow-lg rounded-lg p-6 border border-red-200">
          <h2 className="text-2xl font-bold text-red-600 mb-4">Connection Error</h2>
          <p className="text-gray-600 mb-4">{error}</p>
          <button
            onClick={() => window.location.reload()}
            className="w-full py-2 px-4 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition duration-200"
          >
            Retry Connection
          </button>
        </div>
      </div>
    );
  }
  return (
    <div className="bg-white">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-6">
            <div className="flex items-center">
              <img className="h-8 w-auto" src="/images/clean_pwa_progressive_web_app_icon_shopping_bag.jpg" alt="ExamAppNG" />
              <span className="ml-2 text-xl font-bold text-gray-900">ExamAppNG - JAMB Coach</span>
            </div>
            <div className="flex items-center space-x-4">
              <Link
                to="/login"
                className="text-gray-500 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium"
              >
                Sign In
              </Link>
              <Link
                to="/register"
                className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md text-sm font-medium"
              >
                Get Started
              </Link>
            </div>
          </div>
        </div>
      </header>

      {/* Hero section */}
      <div className="relative bg-gradient-to-br from-blue-50 to-green-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
          <div className="text-center">
            <h1 className="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
              Ace Your <span className="text-blue-600">JAMB Exam</span>
            </h1>
            <p className="mt-3 max-w-md mx-auto text-base text-gray-500 sm:text-lg md:mt-5 md:text-xl md:max-w-3xl">
              AI-powered JAMB coaching app with personalized questions, smart analytics, and comprehensive practice for all 5 subjects.
            </p>
            <div className="mt-5 max-w-md mx-auto sm:flex sm:justify-center md:mt-8">
              <div className="rounded-md shadow">
                <Link
                  to="/register"
                  className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 md:py-4 md:text-lg md:px-10"
                >
                  Start Practicing Free
                </Link>
              </div>
              <div className="mt-3 rounded-md shadow sm:mt-0 sm:ml-3">
                <Link
                  to="/login"
                  className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-blue-600 bg-white hover:bg-gray-50 md:py-4 md:text-lg md:px-10"
                >
                  Sign In
                </Link>
              </div>
            </div>
          </div>
        </div>
        
        {/* Hero image */}
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="relative rounded-lg overflow-hidden shadow-xl">
            <img
              className="w-full h-64 object-cover sm:h-72 md:h-96"
              src="/images/nigerian-jamb-exam-students-computer-lab-study.jpg"
              alt="Nigerian students practicing for JAMB exams"
            />
            <div className="absolute inset-0 bg-blue-600 mix-blend-multiply opacity-30"></div>
          </div>
        </div>
      </div>

      {/* Features section */}
      <div className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-base text-blue-600 font-semibold tracking-wide uppercase">Features</h2>
            <p className="mt-2 text-3xl font-extrabold text-gray-900 sm:text-4xl">
              Everything you need to succeed
            </p>
            <p className="mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto">
              Our comprehensive platform provides all the tools and resources you need to excel in your JAMB examination.
            </p>
          </div>

          <div className="mt-20">
            <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
              {features.map((feature) => (
                <div key={feature.name} className="pt-6">
                  <div className="flow-root bg-gray-50 rounded-lg px-6 pb-8">
                    <div className="-mt-6">
                      <div>
                        <span className="inline-flex items-center justify-center p-3 bg-blue-500 rounded-md shadow-lg">
                          <feature.icon className="h-6 w-6 text-white" aria-hidden="true" />
                        </span>
                      </div>
                      <h3 className="mt-8 text-lg font-medium text-gray-900 tracking-tight">{feature.name}</h3>
                      <p className="mt-5 text-base text-gray-500">{feature.description}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Subject showcase */}
      <div className="py-16 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-3xl font-extrabold text-gray-900">Practice All JAMB Subjects</h2>
            <p className="mt-4 text-lg text-gray-500">
              Comprehensive coverage of Mathematics, Physics, Chemistry, Biology, and English Language
            </p>
          </div>
          
          <div className="mt-12 grid grid-cols-2 gap-8 md:grid-cols-5">
            <div className="col-span-1 flex justify-center items-center">
              <div className="text-center">
                <img className="h-20 w-20 mx-auto rounded-lg" src="/images/clean_mathematics_equations_chalkboard_background.jpg" alt="Mathematics" />
                <p className="mt-2 text-sm font-medium text-gray-900">Mathematics</p>
              </div>
            </div>
            <div className="col-span-1 flex justify-center items-center">
              <div className="text-center">
                <img className="h-20 w-20 mx-auto rounded-lg" src="/images/physics_laboratory_equipment_collection.jpg" alt="Physics" />
                <p className="mt-2 text-sm font-medium text-gray-900">Physics</p>
              </div>
            </div>
            <div className="col-span-1 flex justify-center items-center">
              <div className="text-center">
                <img className="h-20 w-20 mx-auto rounded-lg" src="/images/Colorful-Standard-Chemistry-Periodic-Table.jpg" alt="Chemistry" />
                <p className="mt-2 text-sm font-medium text-gray-900">Chemistry</p>
              </div>
            </div>
            <div className="col-span-1 flex justify-center items-center">
              <div className="text-center">
                <img className="h-20 w-20 mx-auto rounded-lg" src="/images/abstract_biology_cellular_data_visualization.jpg" alt="Biology" />
                <p className="mt-2 text-sm font-medium text-gray-900">Biology</p>
              </div>
            </div>
            <div className="col-span-1 flex justify-center items-center">
              <div className="text-center">
                <img className="h-20 w-20 mx-auto rounded-lg" src="/images/classic-english-literature-book-covers-collage.jpg" alt="English" />
                <p className="mt-2 text-sm font-medium text-gray-900">English</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Testimonials */}
      <div className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-3xl font-extrabold text-gray-900">Student Success Stories</h2>
            <p className="mt-4 text-lg text-gray-500">
              See how ExamAppNG has helped thousands of students achieve their goals
            </p>
          </div>
          
          <div className="mt-12 grid grid-cols-1 gap-8 lg:grid-cols-2">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-gray-50 rounded-lg p-8">
                <div className="flex items-center">
                  <img className="h-12 w-12 rounded-full object-cover" src={testimonial.image} alt={testimonial.name} />
                  <div className="ml-4">
                    <h4 className="text-lg font-medium text-gray-900">{testimonial.name}</h4>
                    <p className="text-sm text-gray-500">{testimonial.role}</p>
                  </div>
                </div>
                <p className="mt-4 text-gray-600 italic">"{testimonial.quote}"</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* CTA section */}
      <div className="bg-blue-600">
        <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
          <h2 className="text-3xl font-extrabold tracking-tight text-white sm:text-4xl">
            <span className="block">Ready to start your JAMB preparation?</span>
            <span className="block text-blue-200">Join thousands of successful students.</span>
          </h2>
          <div className="mt-8 flex lg:mt-0 lg:flex-shrink-0">
            <div className="inline-flex rounded-md shadow">
              <Link
                to="/register"
                className="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-blue-600 bg-white hover:bg-blue-50"
              >
                Get started for free
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-800">
        <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="flex justify-center items-center mb-4">
              <img className="h-8 w-auto" src="/images/clean_pwa_progressive_web_app_icon_shopping_bag.jpg" alt="ExamAppNG" />
              <span className="ml-2 text-xl font-bold text-white">ExamAppNG - JAMB Coach</span>
            </div>
            <p className="text-gray-400">
              AI-powered JAMB coaching for Nigerian students. Achieve your university admission goals with ExamAppNG.
            </p>
            <div className="mt-4 flex justify-center space-x-6">
              <span className="text-gray-400 text-sm">
                © 2025 ExamAppNG - JAMB Coach. Built for Nigerian students.
              </span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}